### PR TITLE
EICNET-2717: Stories - Posting date is wrong by default

### PR DESCRIPTION
**Pull request by 4hardfire**
### Fixes

- Apply patch to fix issue with default publication date when node is not published;
- Show the same date format for News and Story CTypes.

### Test

- [x] Create a new story or news in draft and set the authored date to 3 days ago
- [x] Edit the node and publish it
- [x] Make sure the publication date is set to today when viewing the node detail page
- [x] Make sure the publication date is shown correctly in overview pages

### CODE REVIEW

**Review by lramarojaona — COMMENTED** [review]
@4hardfire , it works, but I'm still getting 2038 when status is in draft

**Comment by 4hardfire** [comment]
> @4hardfire , it works, but I'm still getting 2038 when status is in draft

It should be fixed! Can check?

**Comment by lramarojaona** [comment]
@4hardfire ,
I got this error:

_InvalidArgumentException: The timestamp must be numeric. in Drupal\Component\Datetime\DateTimePlus::createFromTimestamp() (line 201 of core/lib/Drupal/Component/Datetime/DateTimePlus.php).

Drupal\Core\Datetime\DateFormatter->format(NULL, 'custom', 'd F Y') (Line: 169)
_preprocess_node_page(Array) (Line: 101)
eic_community_preprocess_page(Array, 'page', Array) (Line: 287)_

I forgot to set the authored date, but I believe most people if not all won't set a date

**Review by lramarojaona — APPROVED** [review]
Ok, it works

**Pull request merged**
