### PR TITLE
EICNET-1214: Overview empty state

### PR DESCRIPTION
**Pull request by speeters1**

### CODE REVIEW

**Review by xwero — COMMENTED** [review]
Maybe add an example of the empty state and no navigation in storybook?

**Comment by Dromadoros** [comment]
> Maybe add an example of the empty state and no navigation in storybook?

Yes I agree, would be nice

**Comment by Askerx9** [comment]
is done @xwero

**Review by xwero — COMMENTED** [review]
I see the added group empty story, but I don't see the empty state text?

**Comment by Askerx9** [comment]
sorry small problem of understanding. I think it's ok now

**Comment by filipvt1** [comment]
@Askerx9 can you handle resolving the conflicts on this branch? It looks to me like there are 2 implementations of the empty state at the moment. One uses the fields no_results and no_results_text while the other uses no_results_title, no_results_body.

To check which version you keep.

**Review by filipvt1 — CHANGES_REQUESTED** [review]
Inside the file lib/themes/eic_community/react/components/Block/ActivityStream/index.js
There is still a reference to the old values: 
```
           <React.Fragment>
              <h3 className="ecl-activity-stream__no-content-header">{this.props.translations.no_results}</h3>
              <p className="ecl-teaser-overview__no-content-message">{this.props.translations.no_results_text}</p>
            </React.Fragment>
```

**Comment by Askerx9** [comment]
Yeeeaaahhhh it's done @filipvt1

**Review by filipvt1 — APPROVED** [review]

**Pull request merged**
