### PR TITLE
EICNET-2649: Display the shared content message in activity stream item.

### PR DESCRIPTION
**Pull request by lramarojaona**
### Tests

- [x] Make sure you run `make build-front`
- [x] As logged-in user share a content to a group, with a message
- [x] Go to the target group acivity stream
- [x] Make sure you see the activity stream item with the message

### CODE REVIEW

**Review by 4hardfire — APPROVED** [review]
It works!

**Comment by 4hardfire** [comment]
Need review from FE dev.

**Comment by lramarojaona** [comment]
@4hardfire , Sorry I didn't see your message for FE review and I've already merged.
Anyway This PR doesn't touch the structure, just fixes a bug in the logic where sometimes the message variable is null.

**Review by AlexisWalravens — COMMENTED** [review]
The line is a bit long but otherwise I guess it's okay.

**Pull request merged**
