### PR TITLE
EICNET-2087: About section in global events

### PR DESCRIPTION
**Pull request by 4hardfire**
### Fixes

- Fix event about page;
- Improve method to retrieve group visibility descriptions;
- Fix coding standards.

### Tests

- [x] As SA/SCM, go to a group event about page -> `/events/<event-name>/about`
- [x] Make sure the page shows an overview about the event permissions and visibility

### CODE REVIEW

**Comment by lramarojaona** [comment]
I'm getting this after a fresh install:
2022-02-23 12_29_39-My event - About _ EIC-community-D8

Also getting a bucnh of errors:
```
User error: "plugin_id" is an invalid render array key in Drupal\Core\Render\Element::children() (line 98 of core/lib/Drupal/Core/Render/Element.php). 
User error: "label" is an invalid render array key in Drupal\Core\Render\Element::children() (line 98 of core/lib/Drupal/Core/Render/Element.php). 
User error: "settings" is an invalid render array key in Drupal\Core\Render\Element::children() (line 98 of core/lib/Drupal/Core/Render/Element.php). 
User error: "title" is an invalid render array key in Drupal\Core\Render\Element::children() (line 98 of core/lib/Drupal/Core/Render/Element.php). 
User error: "description" is an invalid render array key in Drupal\Core\Render\Element::children() (line 98 of core/lib/Drupal/Core/Render/Element.php).
...
```

**Comment by 4hardfire** [comment]
@lramarojaona I forgot to add the twig template. Can you re-test?

**Comment by lramarojaona** [comment]
It works better indeed, but I still get a bunch of errors:
```
User error: "49" is an invalid render array key in Drupal\Core\Render\Element::children() (line 98 of core/lib/Drupal/Core/Render/Element.php). 
User error: "47" is an invalid render array key in Drupal\Core\Render\Element::children() (line 98 of core/lib/Drupal/Core/Render/Element.php). 
User error: "48" is an invalid render array key in Drupal\Core\Render\Element::children() (line 98 of core/lib/Drupal/Core/Render/Element.php). 
...
```
And the organisation type I selected is not shown:
2022-02-24 10_20_12-My event - About _ EIC-community-D8

Can you create a follow-up ticket for this?

**Review by lramarojaona — APPROVED** [review]

**Comment by 4hardfire** [comment]
Here is the follow-up ticket -> https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-2114.

**Pull request merged**
