### PR TITLE
[EICNET-1692] fix: Remove the url alias field from the join form

### PR DESCRIPTION
**Pull request by korhankale**
## To Test

- [ ] Go to the join group page
- [ ] You shouldn't see the URL alias field anymore

### CODE REVIEW

**Comment by lramarojaona** [comment]
@korhankale , I don't see the URL alias field when being on develop branch, is this needed? (I guess it's better like you did, but I don't how to reproduce the initial issue)

**Comment by korhankale** [comment]
> @korhankale , I don't see the URL alias field when being on develop branch, is this needed? (I guess it's better like you did, but I don't how to reproduce the initial issue)

It is displayed only to users who are allowed to edit them actually
image

**Comment by lramarojaona** [comment]
@korhankale ,
Are you talking about this page? `http://localhost:8081/groups/group-4/join`

**Comment by korhankale** [comment]
> @korhankale , Are you talking about this page? `http://localhost:8081/groups/group-4/join`

Yes, here's an example (use the admin account please): https://qa-eic-7998fed89ac0.victhorious.com/community/groups/test-empty-states-private-group-eicnet/join?destination=/community/groups/test-empty-states-private-group-eicnet

**Pull request merged**
