### PR TITLE
Feature/eicnet 749 implement missing group features

### PR DESCRIPTION
**Pull request by lramarojaona**
Test:

- Create a group
- Edit the group
- Enable Members and Wiki features
- Group menu item should be created and visible for Members and Wiki
- Group permission 'access members overview' should be set for group-member group-admin and group-owner roles
- Disable Members and Wiki features
- Group menu item should be disabled for Members and Wiki
- Group permission 'access members overview' should be removed for group-member group-admin and group-owner roles

There are no permissions associated for Wiki pages.

### CODE REVIEW

**Review by 4hardfire — CHANGES_REQUESTED** [review]
I believe the configuration for the group feature **GroupWiki** is missing. When I enable/disable the Wiki, the menu item is correctly created/disabled but the permission "create group_node:wiki_page entity" never changes. Can you have a look?

Also, in **EicGroupsGroupFeaturePluginBase.php**, my IDE is throwing an exception in the method **handlePermissions** because the  **addRolePermissionsToGroup** (line 129) and **removeRolePermissionsFromGroup** (line 133) expects and GroupPermission and not GroupPermissionInterface.

**Comment by lramarojaona** [comment]
> 
> 
> I believe the configuration for the group feature **GroupWiki** is missing. When I enable/disable the Wiki, the menu item is correctly created/disabled but the permission "create group_node:wiki_page entity" never changes. Can you have a look?
> 
> Also, in **EicGroupsGroupFeaturePluginBase.php**, my IDE is throwing an exception in the method **handlePermissions** because the **addRolePermissionsToGroup** (line 129) and **removeRolePermissionsFromGroup** (line 133) expects and GroupPermission and not GroupPermissionInterface.

@4hardfire , I added the missing configuration for the Wiki feature.
For some reason the "Add wiki page" link doesn't show up in the "Post content" block (the link is correctly being added in the getGroupOperationLinks but it seems to be stripped out somehwere)

Also, regarding the handlePermissions method, can you check again?
As I'm getting a **Drupal\group_permissions\Entity\GroupPermission** and not the interface.

**Comment by 4hardfire** [comment]
> > I believe the configuration for the group feature **GroupWiki** is missing. When I enable/disable the Wiki, the menu item is correctly created/disabled but the permission "create group_node:wiki_page entity" never changes. Can you have a look?
> > Also, in **EicGroupsGroupFeaturePluginBase.php**, my IDE is throwing an exception in the method **handlePermissions** because the **addRolePermissionsToGroup** (line 129) and **removeRolePermissionsFromGroup** (line 133) expects and GroupPermission and not GroupPermissionInterface.
> 
> @4hardfire , I added the missing configuration for the Wiki feature.
> For some reason the "Add wiki page" link doesn't show up in the "Post content" block (the link is correctly being added in the getGroupOperationLinks but it seems to be stripped out somehwere)
> 
> Also, regarding the handlePermissions method, can you check again?
> As I'm getting a **Drupal\group_permissions\Entity\GroupPermission** and not the interface.

@lramarojaona,
The wiki menu item is now working properly. The "Add wiki page" is being removed because I thought the user was supposed to add a wiki page through the wiki section. Should we change this?
Concerning the exception in my IDE, is still happening. See screenshot:
image

**Review by 4hardfire — APPROVED** [review]
Seems ok to me now.

**Pull request merged**
