### PR TITLE
[EICNET-1746]feat: Add field search api event weight state + teaser event

### PR DESCRIPTION
**Pull request by Dromadoros**
How to test:

- [x] Go to organisations details and be sure you have at least more than 4 events
- [x] See if you have max 3 events listed in the block events
- [x] Verify if you see the teaser image in the teaser
- [x] Also check that you have remote event label if remote or address if on site (city, country)
- [x] Check if it's ordered by ongoing, future then past

### CODE REVIEW

**Review by 4hardfire — CHANGES_REQUESTED** [review]
I am having 2 issues when updating an event from the organisation overview page:

`Notice: Undefined index: in Drupal\eic_groups\EICGroupsHelper::formatAddress() (line 980 of /var/www/html/lib/modules/eic_groups/src/EICGroupsHelper.php)`

`Twig\Error\RuntimeError: The merge filter only works with arrays or "Traversable", got "object" as first argument. in twig_array_merge() (line 142 of /var/www/html/lib/themes/eic_community/patterns/compositions/event/event.teaser.html.twig).`

**Comment by 4hardfire** [comment]
@Dromadoros the previous issue seems fixed. However, when using location "On site" it only shows the city and country is missing. Is it supposed?

**Comment by Dromadoros** [comment]
> @Dromadoros the previous issue seems fixed. However, when using location "On site" it only shows the city and country is missing. Is it supposed?

You need to put the taxonomy Country field and also the City in the address from Location field

**Review by 4hardfire — APPROVED** [review]
It works!

**Pull request merged**
