### PR TITLE
Feature/eicnet 2913 org membership job title

### PR DESCRIPTION
**Pull request by lramarojaona**
### Tests

- [x] Go to the organisation manage members page `/organisations/european-innovation-council-eic/members`
- [x] Give some job titles to some members, including Owner and Admin
- [x] Go the organisation detail page
- [x] Make sure you see the members (max 6), ordered by the job title's weight (`/admin/structure/taxonomy/manage/job_titles/overview`)
- [x] Edit the organisation
- [x] Add some items under the `Team` tab
- [x] Go the organisation detail page
- [x] Make sure you the iteams you just added instead of the previous items
- [x] Log in as GO/GA (non power user)
- [x] Edit a membership and make sure you cannot change the job title

### CODE REVIEW

**Review by 4hardfire — CHANGES_REQUESTED** [review]
Should we also make sort by taxonomy name alphabetically when the weight field is the same. After a site install the weights are all set to 0 and for some reason the sort was not according to what I was seeing in the taxonomy overview UI.
Can you have a look?

**Comment by lramarojaona** [comment]
> Should we also make sort by taxonomy name alphabetically when the weight field is the same. After a site install the weights are all set to 0 and for some reason the sort was not according to what I was seeing in the taxonomy overview UI. Can you have a look?

You're right, this is fixed.

**Review by 4hardfire — APPROVED** [review]
It works!

**Comment by Sigtechnica** [comment]
verified it works!

**Pull request merged**
