### PR TITLE
EICNET-2204: Group teaser archived status

### PR DESCRIPTION
**Pull request by 4hardfire**
### Improvements

- Add moderation state in events overview;
- Send group moderation state to the theme variables so that it can be rendered as a tag.

### Todo

- [x] Re-factor group teaser twig template so that it renders the moderation state if not empty. The variable name is `group_state`.

### Test

**As Anonymous and Trusted user:**

- [x] Make sure there are public archived events in the platform
- [x] Go to /events
- [x] Make sure "Archived" label is shown for archived events
- [x] Go to the homepage and make sure you have at least 1 public archived group listed there
- [x] Make sure the "Archived" label is shown

### CODE REVIEW

**Review by lramarojaona — CHANGES_REQUESTED** [review]
@4hardfire ,
In both cases (anonymous or TU), I don't see archived events in the homepage.

**Comment by 4hardfire** [comment]
> @4hardfire , In both cases (anonymous or TU), I don't see archived events in the homepage.

Done!

**Comment by lramarojaona** [comment]
@4hardfire ,
As anonymous I still see the Archived label on the Homepage.

**Comment by 4hardfire** [comment]
> Anonymous still sees the Archived label on the homepage

@lramarojaona, I forgot to update the test scenarios. In fact, only the group visibility is shown for authenticated users because anonymous can only see public groups but the archived label should be shown for both.

**Review by lramarojaona — APPROVED** [review]
Ok, it works

**Pull request merged**
