### PR TITLE
EICNET-2915: Remove member profile related job title.

### PR DESCRIPTION
**Pull request by lramarojaona**
### Tests

- [x] As SA, edit a member profile and make sure there is no Job title field anymore

### Remark

- To be merged after https://github.com/EIC-EA/EIC-community-D8/pull/2040

### CODE REVIEW

**Review by 4hardfire — CHANGES_REQUESTED** [review]
@lramarojaona I made a quick find in the theme and I still found some references in the `\lib\themes\eic_community\includes\preprocess\users\user.inc` (function **_eic_community_get_user_job_titles**). Can you have a look?
Also when I access the user profile page (`/users/<username>`) I get an error `InvalidArgumentException: Field field_vocab_job_title is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 587 of /var/www/html/web/core/lib/Drupal/Core/Entity/ContentEntityBase.php).`

**Comment by lramarojaona** [comment]
> @lramarojaona I made a quick find in the theme and I still found some references in the `\lib\themes\eic_community\includes\preprocess\users\user.inc` (function **_eic_community_get_user_job_titles**). Can you have a look? Also when I access the user profile page (`/users/<username>`) I get an error `InvalidArgumentException: Field field_vocab_job_title is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 587 of /var/www/html/web/core/lib/Drupal/Core/Entity/ContentEntityBase.php).`

@4hardfire , are you sure? I can't find this function, and I don't have any error on the user page. Can you re-check?

**Review by 4hardfire — CHANGES_REQUESTED** [review]
I still can find the reference to the field "field_vocab_job_title" in the theme. And I still have the error.

**Comment by lramarojaona** [comment]
> I still can find the reference to the field "field_vocab_job_title" in the theme. And I still have the error.

@4hardfire , you were right, I forgot to commit that file. It is fixed now.

**Review by 4hardfire — APPROVED** [review]
It works!

**Pull request merged**
