### PR TITLE
EICNET-2804: [Event/stories overview page] Cannot search for my events or My stories (timeout)

### PR DESCRIPTION
**Pull request by 4hardfire**
### Fixes

- Change "My groups & content only" facet label in global events overview;
- Implement missing getPrefilteredGroupFieldId() method in GlobalEventSourceType.

### Todo

- ~Change label "My groups" into "My events" in the list of selected facets~

### Test

- [x] As TU, go to /events
- [x] Make sure you have the filter "My events & content only" (before it was called "My groups & content only")
- [x] Click on the filter
- [x] Make sure list is filtered by your Events only

### CODE REVIEW

**Comment by lramarojaona** [comment]
It works, but there is still a wrong label. When you select "My events & content only" you see the "My groups" filter:
EICNET-2804

**Comment by lramarojaona** [comment]
Ah it's in the todo

**Comment by 4hardfire** [comment]
> Ah it's in the todo

@lramarojaona This has been fixed. Can you build the FE assets and re-test it?

**Review by lramarojaona — APPROVED** [review]
Ok, it works!

**Pull request merged**
