### PR TITLE
[EICNET-2066]feat: Implement group archived check for different entity/action

### PR DESCRIPTION
**Pull request by Dromadoros**
How to test it:

- [ ] Permissions/restrictions need to be respected following this table:
image

### CODE REVIEW

**Review by 4hardfire — COMMENTED** [review]
Group content that is archived cannot be found in the group overviews. Shouldn't we at least show the content to the owner?

**Review by 4hardfire — CHANGES_REQUESTED** [review]
I faced a cache issue:

- As TU, create a discussion in a group
- Add some comments
- Log in as DA in another browser
- Archive the group
- As TU (using the previous session) go to the discussion
- The reply button in the comments is still shown

Note: the reply button will show up until we clear the cache

**Comment by Dromadoros** [comment]
> 

Hey that's the design decided for now: https://www.figma.com/file/XUeM6K26lN6D0VXUMsUdm6/branch/Htq0RAsYksiVdQjUwAx4Gd/Website-UI?node-id=14102%3A72212

**Comment by Dromadoros** [comment]
> Group content that is archived cannot be found in the group overviews. Shouldn't we at least show the content to the owner?

Normally discussion and library content are ok. I added also news and the video has been added by you in a PR

**Comment by Dromadoros** [comment]
> I faced a cache issue:
> 
> * As TU, create a discussion in a group
> * Add some comments
> * Log in as DA in another browser
> * Archive the group
> * As TU (using the previous session) go to the discussion
> * The reply button in the comments is still shown
> 
> Note: the reply button will show up until we clear the cache

I added the group cache tags, tested it, should be ok now

**Review by 4hardfire — APPROVED** [review]
Looks good to me!

**Pull request merged**
