### PR TITLE
[EICNET-2390]fix: do not show links for archived group

### PR DESCRIPTION
**Pull request by Dromadoros**
How to test:

- [x] Archive a group
- [x] Go into it NOT AS SUPER USER but as GO/SA/SCM
- [x] You should not see "post content" and group management operations except the request delete

### CODE REVIEW

**Review by 4hardfire — CHANGES_REQUESTED** [review]
As GO I get access denied when accessing the archived group. Can you have a look?

**Comment by Dromadoros** [comment]
Should be ok now, I pushed to workflow archived state published to true

**Review by 4hardfire — COMMENTED** [review]
As GA (not SA/SCM), I can now access the archived group. However, I cannot see the "Group managment" dropdown and the last step of your test scenario says I should be able to request delete or archival. Is this only for SA/SCM users?

**Comment by Dromadoros** [comment]
You're right dude, it's handled now in the canRequest method!

**Review by 4hardfire — APPROVED** [review]
It works!

**Pull request merged**
