### PR TITLE
Feature/eicnet 2853 group permission revisions

### PR DESCRIPTION
**Pull request by lramarojaona**
### Tests

- [x] Install a dump from PROD
- [x] Get the result of `drush sqlq "SELECT count(*) FROM group_permission_revision;"`
- [x] Run `drush updb -y`
- [x] Get the result of `drush sqlq "SELECT count(*) FROM group_permission_revision;"` and make sure you have the exact same number as the number of existing groups (+/- 7000 items)
- [x] Edit a group and enable/disable some features
- [x] Get the result of `drush sqlq "SELECT count(*) FROM group_permission_revision;"` and make sure you have the exact same number as the number of existing groups (no new revision should be created)

### TODO

- Check if cache must be explictely cleared, or if it's already done upon the save() function.

### CODE REVIEW

**Review by 4hardfire — CHANGES_REQUESTED** [review]
The last step failled. After I edit a group and disable/enable some permissions, for some reason I endup with one more revision. The number of groups on my side is 7116 and now I have 7117 group permission revisions.

**Comment by 4hardfire** [comment]
@lramarojaona if you edit the following group -> `/groups/coaching/edit` and disable 2 features, I end up with 1 more revision.

**Comment by lramarojaona** [comment]
> @lramarojaona if you edit the following group -> `/groups/coaching/edit` and disable 2 features, I end up with 1 more revision.

Ok, I fixed it, can you re-try?

**Review by 4hardfire — APPROVED** [review]
Ok it works!

**Pull request merged**
