### PR TITLE
Feature/eicnet topics details fe

### PR DESCRIPTION
**Pull request by Askerx9**
### What I did

- [ ] add topic in storybook (http://localhost:9000/?path=/story/bundles-topic--topic-overview)
- [ ] slice elements

### CODE REVIEW

**Review by filipvt1 — CHANGES_REQUESTED** [review]
The group teaser looks different. In a recent commit there was some padding added to the teaser component. Because of this the image received some additional padding and doesn't align with the border of the teaser anymore. Either remove the padding for group teaser or pull the image back with negative margins.

**Comment by Askerx9** [comment]
ha yes you right @filipvt1 now it's better

**Review by filipvt1 — APPROVED** [review]

**Review by filipvt1 — CHANGES_REQUESTED** [review]
I would apply the zero padding specifically for the group teaser. Because the group teaser is shown on different pages and is still broken there.

**Comment by Askerx9** [comment]
@filipvt1 so weird but normally with the recent commit it's good now

**Review by filipvt1 — APPROVED** [review]

**Pull request closed without merging**
