### PR TITLE
EICNET-2929: Duplicated item in news and stories in the email digest

### PR DESCRIPTION
**Pull request by 4hardfire**
### Fixes

- Avoid triggering duplicated notification message about content of interest.

### Test

- [x] As TU, follow a topic of interest
- [x] Also make sure you have enabled the notifications about terms of interest
- [x] As SA, create a new Story with that topic and publish it
- [x] Edit the story and create a new draft
- [x] Publish the draft
- [x] Go to weekly digest test UI -> `/admin/config/eic/digest`
- [x] Select the TU, set the date for 1 week from now and trigger the weekly diggest
- [x] Make sure the TU received a notification and the story is not shown as duplicated

### CODE REVIEW

**Comment by lramarojaona** [comment]
It seems there an issue with Story message creation, I never get notified (digest) about that story

**Comment by 4hardfire** [comment]
> It seems there an issue with Story message creation, I never get notified (digest) about that story

@lramarojaona can you test again? I received the notifications on my side. I also improved the test scenarios.

**Comment by 4hardfire** [comment]
@lramarojaona the issue should now be fixed! Can you re-test?

**Review by lramarojaona — APPROVED** [review]
Ok, it works!

**Pull request merged**
