### PR TITLE
[EICNET-1396] fix: Some PHPStan error fixes

### PR DESCRIPTION
**Pull request by korhankale**
This PR fixes some errors reported by PHPStan

### CODE REVIEW

**Review by lramarojaona — COMMENTED** [review]
@korhankale , that's nice.
Does the PHPCS run on your local?

**Comment by korhankale** [comment]
> @korhankale , that's nice.
> Does the PHPCS run on your local?

Yeah it runs but didn't fixed any issue on that part yet, however I see that we have some strang line breaks on function calls on this PR, I'll fix them

**Comment by lramarojaona** [comment]
> 
> 
> > @korhankale , that's nice.
> > Does the PHPCS run on your local?
> 
> Yeah it runs but didn't fixed any issue on that part yet, however I see that we have some strang line breaks on function calls on this PR, I'll fix them

What I mean, is that some of the rules don't seem to be applied.
When I do a commit from the container, I get this (just as an example):

```
FILE: ...les/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php
----------------------------------------------------------------------
FOUND 11 ERRORS AFFECTING 9 LINES
----------------------------------------------------------------------
 30 | ERROR | Missing short description in doc comment
 35 | ERROR | Missing short description in doc comment
 40 | ERROR | Missing short description in doc comment
 48 | ERROR | Missing parameter comment
 49 | ERROR | Missing parameter comment
 49 | ERROR | Missing parameter type
 50 | ERROR | Missing parameter comment
 50 | ERROR | Missing parameter type
 51 | ERROR | Missing parameter comment
 52 | ERROR | Missing parameter comment
 53 | ERROR | Missing parameter comment
----------------------------------------------------------------------

Time: 314ms; Memory: 12MB
```

**Comment by lramarojaona** [comment]
Ok, just discussed with @korhankale , this will be a seperate track

**Review by lramarojaona — APPROVED** [review]

**Pull request merged**
