### PR TITLE
EICNET-1718: Add missing read more links to topic related content views.

### PR DESCRIPTION
**Pull request by lramarojaona**
### Tests

- [x] Go on a Topic detail page which has related content (for each content type)
- [x] Check that we have a "Show more" link for each block
- [x] Check that you have correct statistics fo Experts and Ogranisations (For experts you need topics of expertise in the member profile)

### CODE REVIEW

**Review by 4hardfire — CHANGES_REQUESTED** [review]
I am facing dependency issues when I try to fresh install the website:

`The service "eic_topics.topics_manager" has a dependency on a non-existent service "eic_user.helper".`

**Comment by lramarojaona** [comment]
> I am facing dependency issues when I try to fresh install the website:
> 
> `The service "eic_topics.topics_manager" has a dependency on a non-existent service "eic_user.helper".`

This is fixed now.

**Review by 4hardfire — CHANGES_REQUESTED** [review]
Found this issue when accessing the detail page:
- `Error: Call to a member function setOption() on null in eic_community_preprocess_group__event() (line 84 of /var/www/html/lib/themes/eic_community/includes/preprocess/groups/event.inc)`

**Comment by 4hardfire** [comment]
> Found this issue when accessing the detail page:
> 
> * `Error: Call to a member function setOption() on null in eic_community_preprocess_group__event() (line 84 of /var/www/html/lib/themes/eic_community/includes/preprocess/groups/event.inc)`

@lramarojaona my enviroment was missing the events search overview page. Although, it's now throwing this issue:

**Review by 4hardfire — CHANGES_REQUESTED** [review]
After a fresh install I am still getting the following errors when accessing a topic detail page:

- `Error: Object of class Drupal\Core\Url could not be converted to string in Drupal\Component\Utility\UrlHelper::parse() (line 170 of /var/www/html/web/core/lib/Drupal/Component/Utility/UrlHelper.php)
#0 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2134): Drupal\Component\Utility\UrlHelper::parse(Object(Drupal\Core\Url))
#1 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2107): Drupal\views\Plugin\views\display\DisplayPluginBase->getMoreUrl()
#2 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2231): Drupal\views\Plugin\views\display\DisplayPluginBase->renderMoreLink()`

- `Warning: strpos() expects parameter 1 to be string, object given in Drupal\Component\Utility\UrlHelper::parse() (line 145 of /var/www/html/web/core/lib/Drupal/Component/Utility/UrlHelper.php)
#0 /var/www/html/web/core/includes/bootstrap.inc(312): _drupal_error_handler_real(2, 'strpos() expect...', '/var/www/html/w...', 145)
#1 [internal function]: _drupal_error_handler(2, 'strpos() expect...', '/var/www/html/w...', 145, Array)
#2 /var/www/html/web/core/lib/Drupal/Component/Utility/UrlHelper.php(145): strpos(Object(Drupal\Core\Url), '://')
#3 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2134): Drupal\Component\Utility\UrlHelper::parse(Object(Drupal\Core\Url))
#4 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2107): Drupal\views\Plugin\views\display\DisplayPluginBase->getMoreUrl()
#5 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2231): Drupal\views\Plugin\views\display\DisplayPluginBase->renderMoreLink()`

- `Warning: strpos() expects parameter 1 to be string, object given in Drupal\Component\Utility\UrlHelper::parse() (line 146 of /var/www/html/web/core/lib/Drupal/Component/Utility/UrlHelper.php)
#0 /var/www/html/web/core/includes/bootstrap.inc(312): _drupal_error_handler_real(2, 'strpos() expect...', '/var/www/html/w...', 146)
#1 [internal function]: _drupal_error_handler(2, 'strpos() expect...', '/var/www/html/w...', 146, Array)
#2 /var/www/html/web/core/lib/Drupal/Component/Utility/UrlHelper.php(146): strpos(Object(Drupal\Core\Url), '?')
#3 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2134): Drupal\Component\Utility\UrlHelper::parse(Object(Drupal\Core\Url))
#4 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2107): Drupal\views\Plugin\views\display\DisplayPluginBase->getMoreUrl()
#5 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2231): Drupal\views\Plugin\views\display\DisplayPluginBase->renderMoreLink()`

**Comment by lramarojaona** [comment]
> After a fresh install I am still getting the following errors when accessing a topic detail page:
> 
>     * `Error: Object of class Drupal\Core\Url could not be converted to string in Drupal\Component\Utility\UrlHelper::parse() (line 170 of /var/www/html/web/core/lib/Drupal/Component/Utility/UrlHelper.php) #0 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2134): Drupal\Component\Utility\UrlHelper::parse(Object(Drupal\Core\Url)) #1 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2107): Drupal\views\Plugin\views\display\DisplayPluginBase->getMoreUrl() #2 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2231): Drupal\views\Plugin\views\display\DisplayPluginBase->renderMoreLink()`
> 
>     * `Warning: strpos() expects parameter 1 to be string, object given in Drupal\Component\Utility\UrlHelper::parse() (line 145 of /var/www/html/web/core/lib/Drupal/Component/Utility/UrlHelper.php) #0 /var/www/html/web/core/includes/bootstrap.inc(312): _drupal_error_handler_real(2, 'strpos() expect...', '/var/www/html/w...', 145) #1 [internal function]: _drupal_error_handler(2, 'strpos() expect...', '/var/www/html/w...', 145, Array) #2 /var/www/html/web/core/lib/Drupal/Component/Utility/UrlHelper.php(145): strpos(Object(Drupal\Core\Url), '://') #3 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2134): Drupal\Component\Utility\UrlHelper::parse(Object(Drupal\Core\Url)) #4 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2107): Drupal\views\Plugin\views\display\DisplayPluginBase->getMoreUrl() #5 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2231): Drupal\views\Plugin\views\display\DisplayPluginBase->renderMoreLink()`
> 
>     * `Warning: strpos() expects parameter 1 to be string, object given in Drupal\Component\Utility\UrlHelper::parse() (line 146 of /var/www/html/web/core/lib/Drupal/Component/Utility/UrlHelper.php) #0 /var/www/html/web/core/includes/bootstrap.inc(312): _drupal_error_handler_real(2, 'strpos() expect...', '/var/www/html/w...', 146) #1 [internal function]: _drupal_error_handler(2, 'strpos() expect...', '/var/www/html/w...', 146, Array) #2 /var/www/html/web/core/lib/Drupal/Component/Utility/UrlHelper.php(146): strpos(Object(Drupal\Core\Url), '?') #3 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2134): Drupal\Component\Utility\UrlHelper::parse(Object(Drupal\Core\Url)) #4 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2107): Drupal\views\Plugin\views\display\DisplayPluginBase->getMoreUrl() #5 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2231): Drupal\views\Plugin\views\display\DisplayPluginBase->renderMoreLink()`

@4hardfire , did you add any content or was it right after a clean install?
I'm not getting any error

**Review by 4hardfire — APPROVED** [review]
Seems ok to me!

**Pull request merged**
