### PR TITLE
Feature/eicnet 1527 group events flags

### PR DESCRIPTION
**Pull request by lramarojaona**
### Tests

- [x] As GO/GA, create an event inside a group
- [x] As GO/GA, check that you can highlight (flag) the created event
- [x] As GM, check that you cannot highlight the event
- [x] Check that you don't have a Recommed flag on any CT

### CODE REVIEW

**Review by 4hardfire — CHANGES_REQUESTED** [review]
I am having an issue when trying to highlight the event as GO/GA:
`Path: /flag/flag/highlight_content/26?destination&token=ULllpXSoa66JI7kTCMKFXf8sjh0RF6txMRrP65ttWlg&_wrapper_format=drupal_ajax. Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: The 'flag highlight_content' permission is required. in Drupal\Core\Routing\AccessAwareRouter->checkAccess() (line 121 of /var/www/html/web/core/lib/Drupal/Core/Routing/AccessAwareRouter.php).`

I believe we there is a permission missing.

**Comment by lramarojaona** [comment]
@4hardfire , I fixed it.

**Comment by 4hardfire** [comment]
@lramarojaona as GM I can highlight an event. I suppose this is not ok.

**Comment by lramarojaona** [comment]
> @lramarojaona as GM I can highlight an event. I suppose this is not ok.

@4hardfire 
I just fixed this issue.

**Comment by 4hardfire** [comment]
@lramarojaona for some reason I cannot create group events. I have this issue in the logs when access the event add form:

`Drupal\Core\Entity\EntityStorageException: Cannot load GroupContent entities for an unsaved entity. in Drupal\group\Entity\Storage\GroupContentStorage->loadByEntity() (line 92 of /var/www/html/web/modules/contrib/group/src/Entity/Storage/GroupContentStorage.php).`

**Comment by lramarojaona** [comment]
> @lramarojaona for some reason I cannot create group events. I have this issue in the logs when access the event add form:
> 
> `Drupal\Core\Entity\EntityStorageException: Cannot load GroupContent entities for an unsaved entity. in Drupal\group\Entity\Storage\GroupContentStorage->loadByEntity() (line 92 of /var/www/html/web/modules/contrib/group/src/Entity/Storage/GroupContentStorage.php).`

@4hardfire , nice catch, it's fixed now

**Review by 4hardfire — APPROVED** [review]
Seems ok to me!

**Pull request merged**
