### PR TITLE
[EICNET-1532]  group content event detailed page front end

### PR DESCRIPTION
**Pull request by Askerx9**
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-1532&quickFilter=26820&quickFilter=26822

### What to be done

- [x] Active link state of events is missing
- [x] There should be more space between title & body text
- [x] Design lists the tag "event"
- [x] Each filetype has its own icon
- [x] Language icon missing?
- [x] Missing socials for sharing
- [x] Subtitle color should be darker gray
- [x] Topics, no underline
- [x] Missing address
- [x] Some icons are different from design
- [x] Share with another group has smaller font
- [ ] Need more spacing between blocks of content
- [ ] The files are sorted alphabetically.
- [x] In case of a remote event, show an icon of a computer screen followed by text 'remote event'. 
- [x] Mobile: event files styling is inconsistent when title is long.

### Remarks

***Active link state of events is missing*** - FIXED
> Need to be check with a BE

***Design lists the tag "event"*** - FIXED,
***Each filetype has its own icon*** - FIXED,
> it's already done in the storybook, it needs to be checked by a BE.

***Missing address*** - FIXED,
***Missing socials for sharing*** - FIXED,
***The files are sorted alphabetically.***
> Need to be check with a BE

***Need more spacing between blocks of content***
> same space that we have on all page

### CODE REVIEW

**Comment by 4hardfire** [comment]
Fixed _**Active link state of events**_

**Comment by 4hardfire** [comment]
Fixed **_Design lists the tag "event"_**

**Comment by 4hardfire** [comment]
Fixed **_Missing address_**

**Comment by 4hardfire** [comment]
Fixed **_Missing socials for sharing_**

**Comment by 4hardfire** [comment]
Fixed **_Each filetype has its own icon_**.
@Askerx9 Remarks: currently the `filelist.html.twig` does not show the right icon for image files (only documents).

**Review by filipvt1 — APPROVED** [review]

**Pull request merged**
