### PR TITLE
EICNET-2736: User account] remove text "explaining" email field since irrelevant

### PR DESCRIPTION
**Pull request by 4hardfire**
### Improvements

- Remove helper text from email field in user profile.

### Test

- [x] As SA/SCM, edit a user account
- [x] Make sure the email field doesn't show any helper text

### CODE REVIEW

**Review by lramarojaona — APPROVED** [review]
It works, but maybe we could make this conditional based on `UserHelper::isSmedUser()`

**Comment by 4hardfire** [comment]
> It works, but maybe we could make this conditional based on `UserHelper::isSmedUser()`

@lramarojaona shouldn't this be removed for all users? I don't understand why we need that condition.

**Comment by lramarojaona** [comment]
> isSmedUser

Some users might be non EU Login users. Btw, `UserHelper::isSmedUser()` is not correct. We should probably check through the cas module. Probably `Drupal\cas\Service\CasUserManager::getCasUsernameForAccount()` ?

**Comment by lramarojaona** [comment]
> > It works, but maybe we could make this conditional based on `UserHelper::isSmedUser()`
> 
> @lramarojaona shouldn't this be removed for all users? I don't understand why we need that condition.

@4hardfire , Some users might be non EU Login users. Btw, `UserHelper::isSmedUser()` is not correct. We should probably check through the cas module. Probably D`rupal\cas\Service\CasUserManager::getCasUsernameForAccount()` ?

**Comment by 4hardfire** [comment]
> > > It works, but maybe we could make this conditional based on `UserHelper::isSmedUser()`
> > 
> > 
> > @lramarojaona shouldn't this be removed for all users? I don't understand why we need that condition.
> 
> @4hardfire , Some users might be non EU Login users. Btw, `UserHelper::isSmedUser()` is not correct. We should probably check through the cas module. Probably D`rupal\cas\Service\CasUserManager::getCasUsernameForAccount()` ?

@lramarojaona It should be fixed. Can you have a look?

**Pull request merged**
