### PR TITLE
Bugfix/ludo 05072021

### PR DESCRIPTION
**Pull request by lramarojaona**
- Added missing dependency in eic_seo module that prevented a clean install
- Fixed a notice in eic_seo AliasCleaner service
- Updated modules and dependencies, including Group module
- Removed the patch for Group revisions as it is now integrated in the module itself
- Patched scheduler_content_moderation_integration moduel to fix a PHP notice
- Fixed oec_group_flex that was throwing a PHP notice upon group creation

### CODE REVIEW

**Comment by xwero** [comment]
> Added missing dependency in eic_seo module that prevented a clean install

This is ok

**Comment by 4hardfire** [comment]
### Test

- [ ] Added missing dependency in eic_seo module that prevented a clean install
- [ ] Fixed a notice in eic_seo AliasCleaner service
- [ ] Updated modules and dependencies, including Group module
- [ ] Removed the patch for Group revisions as it is now integrated in the module itself
- [ ] Patched scheduler_content_moderation_integration moduel to fix a PHP notice
- [ ] Fixed oec_group_flex that was throwing a PHP notice upon group creation

**Review by 4hardfire — APPROVED** [review]
Seems ok to me!

**Comment by lramarojaona** [comment]
Fixed merge conflict with composer.lock.
Following modules now also updated to their latest version and seem ok:
- grequest
- group_content_menu
- Drupal core

**Pull request merged**
